<?php

namespace Tests\Unit;

use App\Models\BlogPost;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class PostTest extends TestCase
{
    use RefreshDatabase;

    protected $post;

    public function setUp() :void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->post = BlogPost::factory()->create();
    }

    function test_a_thread_has_replies()
    {
        $this->assertInstanceOf('Illuminate\Database\Eloquent\Collection', $this->post->comments);
    }
}
